//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleBrotherEye.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeValue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CodeValue()
        {
            this.Events = new HashSet<Event>();
            this.Events1 = new HashSet<Event>();
        }
    
        public int CodeTableId { get; set; }
        public int CodeValue1 { get; set; }
        public string Description { get; set; }
        public bool Deleted { get; set; }
    
        public virtual CodeTable CodeTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events1 { get; set; }
    }
}
