//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleBrotherEye.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.EditHistories = new HashSet<EditHistory>();
        }
    
        public int EventId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Character_Cd { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int RewardType_Cd { get; set; }
    
        public virtual CodeValue Character { get; set; }
        public virtual CodeValue RewardType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EditHistory> EditHistories { get; set; }
    }
}
